# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: FOAM Developer portal
author: FOAM
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
#url: https://f-o-a-m.github.io/
root: /foam.developer/

# Writing
relative_link: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ../node_modules/foam-hexo-theme-doc

public_dir: public

# mermaid chart 
mermaid: ## mermaid url https://github.com/knsv/mermaid 
  enable: true  # default true 
  version: "7.1.2" # default v7.1.2 
  options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js 
    #startOnload: true  // default true 

theme_config:
  favicon: /images/favicon.ico
  google_analytics: UA-111781922-3
  # support:
  #   link_text: Raise an Issue on Github
  #   link_url: https://github.com/f-o-a-m/foam.developer/issues/new
  #   navigation: true
  #   navigation_label: SUPPORT AND FEEDBACK

# turns off breaks on new line in md file. To get a line break add three spaces to the end of the line before the break
marked:
  breaks: false

ignore:
  # development only: ignore sub node_modules when `npm link hexo-theme-doc`
  - '**/node_modules/**/*node_modules'
